export const texts = [
	"the quick brown fox jumps over the lazy dog the dog barks loudly in surprise as the fox swiftly escapes into the nearby woods the sun begins to set casting a warm glow over the tranquil scene in a small village nestled among the rolling hills the townspeople go about their daily routines children laugh and play in the meadows while the farmers tend to their crops and livestock life flows peacefully like a gentle stream",
	"amelia gazed at the stars twinkling in the midnight sky contemplating the vastness of the universe she wondered about the mysteries of life and the possibility of extraterrestrial civilizations beyond our solar system the majestic waterfall cascades down the cliff creating a mesmerizing spectacle of water and mist tourists from all around the world visit this natural wonder capturing its beauty in photographs and memories",
	"the old library stands as a testament to the wisdom of ages past dusty shelves line the walls holding countless volumes of knowledge each book holds the power to transport readers to new worlds and realms of imagination as the orchestra begins to play the ballet dancers gracefully glide across the stage telling a story through their movements the audience is captivated by the elegance and emotion portrayed in this timeless art form",
	"in the heart of the city bustling with activity people from diverse backgrounds come together the aroma of street food fills the air as laughter and conversations intertwine creating a tapestry of cultures and experiences the sun rises over the horizon casting a golden hue over the vast savannah herds of wildebeests and zebras graze peacefully while lions patiently observe waiting for the opportune moment to hunt",
	"in a quaint cafe friends gather over cups of steaming coffee and share stories of love adventure and heartbreak the clinking of mugs and laughter create an atmosphere of warmth and camaraderie as the storm clouds gather lightning illuminates the darkened sky followed by the rumble of thunder raindrops dance on rooftops bringing life to the earth and a sense of renewal to all living beings",
	"the scent of blooming flowers fills the air as spring awakens nature from its slumber bees buzz around collecting nectar and birds sing melodies of joy in celebration of new beginnings a lone traveler embarks on a journey through vast landscapes encountering breathtaking mountains serene lakes and hidden valleys with each step a sense of wonder and discovery fills the heart",
	"in a distant galaxy two stars embrace in a cosmic dance painting the skies with shimmering hues planets orbit them carrying the potential for life and the mysteries of the cosmos a lighthouse stands tall on a rocky coastline guiding ships safely through treacherous waters its light pierces through the darkness offering hope and guidance to those in need",
	"underneath the ocean's surface a coral reef teems with life and vibrant colors fish of all shapes and sizes swim through intricate coral formations creating a mesmerizing underwater symphony in the heart of a bustling market artisans display their crafts from around the world the air is filled with the sounds of bargaining and the aroma of exotic spices creating a sensory feast for visitors",
	"as the sun sets on a warm summer evening families gather around a bonfire on the beach laughter and stories fill the air as marshmallows roast over the crackling flames high in the mountains a waterfall plunges into a crystal-clear pool below the sound of rushing water is soothing and the surrounding trees provide a sense of serenity and tranquility",
	"in a small village villagers prepare for a festive celebration colorful decorations adorn the streets and the joyful sounds of music and dance create an atmosphere of unity and happiness amidst the ruins of an ancient civilization archaeologists uncover artifacts that offer glimpses into the past each artifact holds a story of its own waiting to be deciphered",
];
